### ISSUE TITLE
Customize name of "After-Event-Party"?

### ISSUE THREAD

**Issue by danleh** [Clemens85/runningdinner#64]
Hi Clemens! First of all, thanks for the amazing website and making it open-source! :)

Would it be possible to make the name of the "After-Event-Party" customizable when creating an event (similar to how the individual meals/courses can be renamed in https://github.com/Clemens85/runningdinner/blob/main/runningdinner-client/webapp/src/admin/dashboard/MealsList.tsx)?

Background/context: We would like to not call it "party" but something like "Gettogether" or "Discussion" or "Meet and Greet" since sometimes people are disappointed or confused if it's not a party but more of a mingling event to get-to-know people from other teams.

**Comment by Clemens85** [comment]
Hi Daniel, 
thanks for the feedback!
I will add a further input for customizing the title of the after event party.
Currently I am a little bit busy, so I cannot promise when this will be productive, but I will come back to you when I start to work on it and if it is live.

**Comment by danleh** [comment]
Thanks for the very quick reply! :) Sure, no worries about the time, I'll just follow this issue for updates.

**Comment by Clemens85** [comment]
Tasks:
- [x] New field in DB for afterEventPartyTitle => Add DB Migration to fill field with old default value ("After-Event-Party")
- [x] Enhance backend for new field (CRU)
- [x] New text input field in client in form with default value of "After-Event-Party" (add helper text)
- [x] Remove translation of old fixed i18n-key (value comes now always from title field in client)
- [x] Use title field for showing party details (maps, public-dinner-event-page)

**Comment by Clemens85** [comment]
Ich habe die Erweiterung vorhin live deployt. 
Ging alles etwas länger weil ich meine CI/CD Pipeline noch umgezogen habe auf ein anderes System und damit jetzt zum ersten Mal deployt habe.

**Comment by danleh** [comment]
Oh wow, das ging ja mega schnell. Vielen Dank dafür! :)
