### ISSUE TITLE
Show map of all participants

### ISSUE THREAD

**Issue by danleh** [Clemens85/runningdinner#74]
Could one see in a tab in the admin panel (or next to the participant list) a map with markers for all participant locations (or kitchen locations)?

**Comment by Clemens85** [comment]
I got also a feedback already for this feature, and this sounds very reasonable and I am going to implement it (will however take some time). 
I wonder however if you were in the same event as the other person that aso had this feature request ;-)

**Comment by danleh** [comment]
Ha, interesting! No, it must have been a different event then. (We are organizing www.mainz-kocht.de right now, with around 250 people)

Thanks a lot for your very quick replies here and taking interest in such featurer requests! ♥️

**Comment by Clemens85** [comment]
Tasks:
- [x] Backend enhancement with endpoint for getting all DinnerRoutes
- [x] Show all team hosts on map with individual color (based e.g. upon team host name and/or all names of the teams)
- [x] Show connection lines for each team on their route with their own color
- [x] Add minimizable window in map for activating / deactivating single team routes
- [x] Fix issues with Google Maps integration also in normal Dinner Route view (Markers don't work anymore with used library, use new lib)
---
- [x] Check mobile view of main navigation still working
- [x] Restructure navigation 
- [x] Own top level menu entry for sending messages
- [x] New Messages page with participant / team and dinner route messages which shows protocols of already sent messages
- [x] Jump to new message sending from this page
- [x] Put Host locations overview link into Teams page that has now enough space 
- [x] Add missing translations & Browser Title
- [x] Remove obsolete redux code
---
- [x] Numbering of teams in single dinner route map view does not make sense (# 1  - # 3)

**Comment by Clemens85** [comment]
Closing this Issue now, due to there was a release yesterday with a first version of this route overview (can be accessed from teams view).
Further improvements are put into an own issue

**Comment by danleh** [comment]
That's amazing, very much looking forward to try this out for the next round! :)
