### ISSUE TITLE
Registration date/time in participant overview

### ISSUE THREAD

**Issue by danleh** [Clemens85/runningdinner#75]
This is useful to de-prioritize participants that registered late.

**Comment by Clemens85** [comment]
Actually the participants are ordered by their registration date, so it should automatically be visible how registered first 
(this ordering may however be destroy when performing manual swaps).
Anyway I can also add the information about the registration time into the participant overview.

**Comment by danleh** [comment]
Exactly, it's because we manually swapped in some people and then lost track of who came first. (So not a very important feature, but a nice little quality-of-life thing) :)

**Comment by Clemens85** [comment]
Added info about subscription date into participant detail form. 
Wanted to put it into the overall list, but this did not fit well, hence it is now in the form (when viewing / editing a participant)
